# Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2 License.
# This product includes software developed at Datadog (https://www.datadoghq.com/) Copyright 2025 Datadog, Inc.

import os
from unittest.mock import MagicMock, patch

import pytest

from azure_agentless_setup.config import Config
from azure_agentless_setup.terraform import (
    MODULE_VERSION,
    _sanitize_name,
    generate_terraform_config,
    generate_tfvars,
)


def _make_config(**overrides) -> Config:
    defaults = dict(
        api_key="test-api-key",
        app_key="test-app-key",
        site="datadoghq.com",
        workflow_id="wf-123",
        scanner_subscription="sub-scanner",
        locations=["eastus"],
        subscriptions_to_scan=["sub-scanner", "sub-other"],
        resource_group="datadog-agentless-scanner",
    )
    defaults.update(overrides)
    return Config(**defaults)


API_KEY_SECRET_ID = "/subscriptions/sub-scanner/resourceGroups/datadog-agentless-scanner/providers/Microsoft.KeyVault/vaults/datadog-abc123/secrets/datadog-api-key"

MODULE_SOURCE = f"git::https://github.com/DataDog/terraform-module-datadog-agentless-scanner//azure/modules"


class TestSanitizeName:
    def test_replaces_hyphens(self):
        assert _sanitize_name("east-us") == "east_us"

    def test_no_hyphens(self):
        assert _sanitize_name("eastus") == "eastus"


class TestGenerateTerraformConfig:
    def test_single_location(self):
        config = _make_config(locations=["eastus"])
        tf = generate_terraform_config(config, "storageacct", API_KEY_SECRET_ID, "ssh-rsa AAAA")

        expected = f"""# Generated by Datadog Agentless Scanner Cloud Shell Setup
# Do not edit manually — rerun the setup script to update

terraform {{
  required_version = ">= 1.0"

  required_providers {{
    azurerm = {{
      source  = "hashicorp/azurerm"
      version = ">= 3.101.0"
    }}
  }}

  backend "azurerm" {{
    storage_account_name = "storageacct"
    container_name       = "tfstate"
    key                  = "datadog-agentless.tfstate"
    subscription_id      = "sub-scanner"
    use_azuread_auth     = true
  }}
}}

provider "azurerm" {{
  features {{}}
  subscription_id = "sub-scanner"
}}

data "azurerm_resource_group" "scanner" {{
  name = "datadog-agentless-scanner"
}}


variable "admin_ssh_key" {{
  description = "SSH public key for scanner VMSS instances"
  type        = string
  sensitive   = true
}}

module "managed_identity" {{
  source              = "{MODULE_SOURCE}/managed-identity?ref={MODULE_VERSION}"
  resource_group_name = data.azurerm_resource_group.scanner.name
  location            = data.azurerm_resource_group.scanner.location
}}

module "roles" {{
  source            = "{MODULE_SOURCE}/roles?ref={MODULE_VERSION}"
  role_name_suffix  = "datadog-agentless-scanner-sub-scan"
  resource_group_id = data.azurerm_resource_group.scanner.id
  principal_id      = module.managed_identity.identity.principal_id
  api_key_secret_id = "{API_KEY_SECRET_ID}"
  scan_scopes       = ["/subscriptions/sub-other", "/subscriptions/sub-scanner"]
}}

module "custom_data" {{
  source    = "{MODULE_SOURCE}/custom-data?ref={MODULE_VERSION}"
  api_key   = "@Microsoft.KeyVault(SecretUri=https://datadog-abc123.vault.azure.net/secrets/datadog-api-key)"
  site      = "datadoghq.com"
  client_id = module.managed_identity.identity.client_id
}}


# --- eastus ---

resource "azurerm_virtual_network" "vnet_eastus" {{
  name                = "vnet-eastus"
  location            = "eastus"
  resource_group_name = data.azurerm_resource_group.scanner.name
  address_space       = ["10.0.0.0/16"]
  tags                = {{ Datadog = "true", DatadogAgentlessScanner = "true" }}
}}

resource "azurerm_subnet" "subnet_eastus" {{
  name                 = "default"
  resource_group_name  = data.azurerm_resource_group.scanner.name
  virtual_network_name = azurerm_virtual_network.vnet_eastus.name
  address_prefixes     = ["10.0.0.0/18"]
}}

resource "azurerm_nat_gateway" "natgw_eastus" {{
  name                = "natgw-eastus"
  location            = "eastus"
  resource_group_name = data.azurerm_resource_group.scanner.name
  sku_name            = "Standard"
  tags                = {{ Datadog = "true", DatadogAgentlessScanner = "true" }}
}}

resource "azurerm_public_ip" "natgw_ip_eastus" {{
  name                = "natgw-ip-eastus"
  location            = "eastus"
  resource_group_name = data.azurerm_resource_group.scanner.name
  sku                 = "Standard"
  sku_tier            = "Regional"
  ip_version          = "IPv4"
  allocation_method   = "Static"
  tags                = {{ Datadog = "true", DatadogAgentlessScanner = "true" }}
}}

resource "azurerm_nat_gateway_public_ip_association" "natgw_ip_assoc_eastus" {{
  nat_gateway_id       = azurerm_nat_gateway.natgw_eastus.id
  public_ip_address_id = azurerm_public_ip.natgw_ip_eastus.id
}}

resource "azurerm_subnet_nat_gateway_association" "subnet_natgw_assoc_eastus" {{
  subnet_id      = azurerm_subnet.subnet_eastus.id
  nat_gateway_id = azurerm_nat_gateway.natgw_eastus.id
}}

module "virtual_machine_eastus" {{
  source                 = "{MODULE_SOURCE}/virtual-machine?ref={MODULE_VERSION}"
  depends_on             = [azurerm_subnet_nat_gateway_association.subnet_natgw_assoc_eastus]
  name                   = "DatadogAgentlessScanner-eastus"
  location               = "eastus"
  resource_group_name    = data.azurerm_resource_group.scanner.name
  admin_ssh_key          = var.admin_ssh_key
  custom_data            = module.custom_data.install_sh
  subnet_id              = azurerm_subnet.subnet_eastus.id
  user_assigned_identity = module.managed_identity.identity.id
}}

"""

        assert tf == expected

    def test_multi_location(self):
        config = _make_config(locations=["eastus", "westeurope"])
        tf = generate_terraform_config(config, "storageacct", API_KEY_SECRET_ID, "ssh-rsa AAAA")

        expected = f"""# Generated by Datadog Agentless Scanner Cloud Shell Setup
# Do not edit manually — rerun the setup script to update

terraform {{
  required_version = ">= 1.0"

  required_providers {{
    azurerm = {{
      source  = "hashicorp/azurerm"
      version = ">= 3.101.0"
    }}
  }}

  backend "azurerm" {{
    storage_account_name = "storageacct"
    container_name       = "tfstate"
    key                  = "datadog-agentless.tfstate"
    subscription_id      = "sub-scanner"
    use_azuread_auth     = true
  }}
}}

provider "azurerm" {{
  features {{}}
  subscription_id = "sub-scanner"
}}

data "azurerm_resource_group" "scanner" {{
  name = "datadog-agentless-scanner"
}}


variable "admin_ssh_key" {{
  description = "SSH public key for scanner VMSS instances"
  type        = string
  sensitive   = true
}}

module "managed_identity" {{
  source              = "{MODULE_SOURCE}/managed-identity?ref={MODULE_VERSION}"
  resource_group_name = data.azurerm_resource_group.scanner.name
  location            = data.azurerm_resource_group.scanner.location
}}

module "roles" {{
  source            = "{MODULE_SOURCE}/roles?ref={MODULE_VERSION}"
  role_name_suffix  = "datadog-agentless-scanner-sub-scan"
  resource_group_id = data.azurerm_resource_group.scanner.id
  principal_id      = module.managed_identity.identity.principal_id
  api_key_secret_id = "{API_KEY_SECRET_ID}"
  scan_scopes       = ["/subscriptions/sub-other", "/subscriptions/sub-scanner"]
}}

module "custom_data" {{
  source    = "{MODULE_SOURCE}/custom-data?ref={MODULE_VERSION}"
  api_key   = "@Microsoft.KeyVault(SecretUri=https://datadog-abc123.vault.azure.net/secrets/datadog-api-key)"
  site      = "datadoghq.com"
  client_id = module.managed_identity.identity.client_id
}}


# --- eastus ---

resource "azurerm_virtual_network" "vnet_eastus" {{
  name                = "vnet-eastus"
  location            = "eastus"
  resource_group_name = data.azurerm_resource_group.scanner.name
  address_space       = ["10.0.0.0/16"]
  tags                = {{ Datadog = "true", DatadogAgentlessScanner = "true" }}
}}

resource "azurerm_subnet" "subnet_eastus" {{
  name                 = "default"
  resource_group_name  = data.azurerm_resource_group.scanner.name
  virtual_network_name = azurerm_virtual_network.vnet_eastus.name
  address_prefixes     = ["10.0.0.0/18"]
}}

resource "azurerm_nat_gateway" "natgw_eastus" {{
  name                = "natgw-eastus"
  location            = "eastus"
  resource_group_name = data.azurerm_resource_group.scanner.name
  sku_name            = "Standard"
  tags                = {{ Datadog = "true", DatadogAgentlessScanner = "true" }}
}}

resource "azurerm_public_ip" "natgw_ip_eastus" {{
  name                = "natgw-ip-eastus"
  location            = "eastus"
  resource_group_name = data.azurerm_resource_group.scanner.name
  sku                 = "Standard"
  sku_tier            = "Regional"
  ip_version          = "IPv4"
  allocation_method   = "Static"
  tags                = {{ Datadog = "true", DatadogAgentlessScanner = "true" }}
}}

resource "azurerm_nat_gateway_public_ip_association" "natgw_ip_assoc_eastus" {{
  nat_gateway_id       = azurerm_nat_gateway.natgw_eastus.id
  public_ip_address_id = azurerm_public_ip.natgw_ip_eastus.id
}}

resource "azurerm_subnet_nat_gateway_association" "subnet_natgw_assoc_eastus" {{
  subnet_id      = azurerm_subnet.subnet_eastus.id
  nat_gateway_id = azurerm_nat_gateway.natgw_eastus.id
}}

module "virtual_machine_eastus" {{
  source                 = "{MODULE_SOURCE}/virtual-machine?ref={MODULE_VERSION}"
  depends_on             = [azurerm_subnet_nat_gateway_association.subnet_natgw_assoc_eastus]
  name                   = "DatadogAgentlessScanner-eastus"
  location               = "eastus"
  resource_group_name    = data.azurerm_resource_group.scanner.name
  admin_ssh_key          = var.admin_ssh_key
  custom_data            = module.custom_data.install_sh
  subnet_id              = azurerm_subnet.subnet_eastus.id
  user_assigned_identity = module.managed_identity.identity.id
}}

# --- westeurope ---

resource "azurerm_virtual_network" "vnet_westeurope" {{
  name                = "vnet-westeurope"
  location            = "westeurope"
  resource_group_name = data.azurerm_resource_group.scanner.name
  address_space       = ["10.0.0.0/16"]
  tags                = {{ Datadog = "true", DatadogAgentlessScanner = "true" }}
}}

resource "azurerm_subnet" "subnet_westeurope" {{
  name                 = "default"
  resource_group_name  = data.azurerm_resource_group.scanner.name
  virtual_network_name = azurerm_virtual_network.vnet_westeurope.name
  address_prefixes     = ["10.0.0.0/18"]
}}

resource "azurerm_nat_gateway" "natgw_westeurope" {{
  name                = "natgw-westeurope"
  location            = "westeurope"
  resource_group_name = data.azurerm_resource_group.scanner.name
  sku_name            = "Standard"
  tags                = {{ Datadog = "true", DatadogAgentlessScanner = "true" }}
}}

resource "azurerm_public_ip" "natgw_ip_westeurope" {{
  name                = "natgw-ip-westeurope"
  location            = "westeurope"
  resource_group_name = data.azurerm_resource_group.scanner.name
  sku                 = "Standard"
  sku_tier            = "Regional"
  ip_version          = "IPv4"
  allocation_method   = "Static"
  tags                = {{ Datadog = "true", DatadogAgentlessScanner = "true" }}
}}

resource "azurerm_nat_gateway_public_ip_association" "natgw_ip_assoc_westeurope" {{
  nat_gateway_id       = azurerm_nat_gateway.natgw_westeurope.id
  public_ip_address_id = azurerm_public_ip.natgw_ip_westeurope.id
}}

resource "azurerm_subnet_nat_gateway_association" "subnet_natgw_assoc_westeurope" {{
  subnet_id      = azurerm_subnet.subnet_westeurope.id
  nat_gateway_id = azurerm_nat_gateway.natgw_westeurope.id
}}

module "virtual_machine_westeurope" {{
  source                 = "{MODULE_SOURCE}/virtual-machine?ref={MODULE_VERSION}"
  depends_on             = [azurerm_subnet_nat_gateway_association.subnet_natgw_assoc_westeurope]
  name                   = "DatadogAgentlessScanner-westeurope"
  location               = "westeurope"
  resource_group_name    = data.azurerm_resource_group.scanner.name
  admin_ssh_key          = var.admin_ssh_key
  custom_data            = module.custom_data.install_sh
  subnet_id              = azurerm_subnet.subnet_westeurope.id
  user_assigned_identity = module.managed_identity.identity.id
}}

"""

        assert tf == expected

    def test_scan_scopes_include_all_subscriptions(self):
        config = _make_config(subscriptions_to_scan=["sub-scanner", "sub-a", "sub-b"])
        tf = generate_terraform_config(config, "storageacct", API_KEY_SECRET_ID, "ssh-rsa AAAA")

        assert 'scan_scopes       = ["/subscriptions/sub-a", "/subscriptions/sub-b", "/subscriptions/sub-scanner"]' in tf

    def test_module_version_pinned(self):
        config = _make_config()
        tf = generate_terraform_config(config, "storageacct", API_KEY_SECRET_ID, "ssh-rsa AAAA")

        assert f"ref={MODULE_VERSION}" in tf

    def test_role_name_suffix_includes_subscription_prefix(self):
        config = _make_config(resource_group="my-custom-rg", scanner_subscription="46aba334-2540-4cfe-b36e-54266afb2bf6")
        tf = generate_terraform_config(config, "storageacct", API_KEY_SECRET_ID, "ssh-rsa AAAA")

        assert 'role_name_suffix  = "my-custom-rg-46aba334"' in tf


class TestGenerateTfvars:
    def test_contains_ssh_key(self):
        tfvars = generate_tfvars("ssh-rsa AAAA test@host")
        assert 'admin_ssh_key = "ssh-rsa AAAA test@host"' in tfvars
