# Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2 License.
# This product includes software developed at Datadog (https://www.datadoghq.com/) Copyright 2025 Datadog, Inc.

"""Terraform wrapper for running init and apply."""

import os
from pathlib import Path
from typing import Optional

from .config import Config
from .errors import TerraformError
from .shell import run_command
from .reporter import Reporter


# Module version to use
MODULE_VERSION = "0.11.12"
MODULE_SOURCE = f"git::https://github.com/DataDog/terraform-module-datadog-agentless-scanner//gcp?ref={MODULE_VERSION}"
MODULE_SOURCE_SA = f"git::https://github.com/DataDog/terraform-module-datadog-agentless-scanner//gcp/modules/agentless-impersonated-service-account?ref={MODULE_VERSION}"


def generate_terraform_config(config: Config, state_bucket: str) -> str:
    """Generate the Terraform configuration."""

    # Build the list of scanned projects for the impersonated SA module
    other_projects_tf = ""
    for project in config.other_projects:
        other_projects_tf += f'''
# Impersonated service account for scanning {project}
module "agentless_impersonated_sa_{project.replace("-", "_")}" {{
  source = "{MODULE_SOURCE_SA}"

  providers = {{
    google = google.{project.replace("-", "_")}
  }}

  scanner_service_account_email = module.datadog_agentless_scanner.scanner_service_account_email
}}

# Enable agentless scanning for {project}
resource "datadog_agentless_scanning_gcp_scan_options" "scan_{project.replace("-", "_")}" {{
  gcp_project_id     = "{project}"
  vuln_host_os       = true
  vuln_containers_os = true
}}
'''

    # Build provider blocks for other projects
    other_providers_tf = ""
    for project in config.other_projects:
        other_providers_tf += f'''
provider "google" {{
  project = "{project}"
  region  = "{config.region}"
  alias   = "{project.replace("-", "_")}"
}}
'''

    tf_config = f'''# Generated by Datadog Agentless Scanner Cloud Shell Setup
# Do not edit manually - rerun the setup script to update

terraform {{
  required_version = ">= 1.0"

  required_providers {{
    google = {{
      source  = "hashicorp/google"
      version = ">= 5.0"
    }}
    datadog = {{
      source  = "DataDog/datadog"
      version = ">= 3.81.0"
    }}
  }}

  backend "gcs" {{
    bucket = "{state_bucket}"
    prefix = "agentless-scanner"
  }}
}}

# Provider for scanner project
provider "google" {{
  project = "{config.scanner_project}"
  region  = "{config.region}"
}}

# Provider for Datadog
provider "datadog" {{
  api_key = var.datadog_api_key
  app_key = var.datadog_app_key
  api_url = "https://api.${{var.datadog_site}}/"
}}
{other_providers_tf}

# Variables
variable "datadog_api_key" {{
  description = "Datadog API key"
  type        = string
  sensitive   = true
}}

variable "datadog_app_key" {{
  description = "Datadog Application key"
  type        = string
  sensitive   = true
}}

variable "datadog_site" {{
  description = "Datadog site"
  type        = string
}}

# Deploy the scanner infrastructure in the scanner project
module "datadog_agentless_scanner" {{
  source = "{MODULE_SOURCE}"

  site     = var.datadog_site
  api_key  = var.datadog_api_key
  vpc_name = "datadog-agentless-scanner"
}}

# Enable agentless scanning for the scanner project
resource "datadog_agentless_scanning_gcp_scan_options" "scanner_project" {{
  gcp_project_id     = "{config.scanner_project}"
  vuln_host_os       = true
  vuln_containers_os = true
}}
{other_projects_tf}
'''

    return tf_config


def generate_tfvars(config: Config) -> str:
    """Generate the terraform.tfvars content."""
    return f'''datadog_api_key = "{config.api_key}"
datadog_app_key = "{config.app_key}"
datadog_site    = "{config.site}"
'''


class TerraformRunner:
    """Runs Terraform commands in a working directory."""

    def __init__(self, config: Config, state_bucket: str, reporter: Reporter):
        self.config = config
        self.state_bucket = state_bucket
        self.reporter = reporter
        self.work_dir: Optional[Path] = None

    def setup_working_directory(self) -> Path:
        """Create and setup the Terraform working directory."""
        # Use a persistent directory in user's home for reuse
        work_dir = Path.home() / ".datadog-agentless-setup" / self.config.scanner_project
        work_dir.mkdir(parents=True, exist_ok=True)

        # Write main.tf
        main_tf = work_dir / "main.tf"
        main_tf.write_text(generate_terraform_config(self.config, self.state_bucket))

        # Write terraform.tfvars
        tfvars = work_dir / "terraform.tfvars"
        tfvars.write_text(generate_tfvars(self.config))

        self.work_dir = work_dir
        return work_dir

    def init(self) -> None:
        """Run terraform init.

        Raises:
            TerraformError: If init fails.
        """
        if not self.work_dir:
            raise TerraformError("Working directory not set up")

        result = run_command(
            ["terraform", "init", "-input=false"],
            capture_output=False,  # Show output to user
        )

        if not result.success:
            raise TerraformError("Terraform init failed")

    def apply(self) -> None:
        """Run terraform apply.

        Raises:
            TerraformError: If apply fails.
        """
        if not self.work_dir:
            raise TerraformError("Working directory not set up")

        result = run_command(
            ["terraform", "apply", "-auto-approve", "-input=false"],
            capture_output=False,  # Show output to user
        )

        if not result.success:
            raise TerraformError("Terraform apply failed")

    def run(self) -> None:
        """Run the full Terraform workflow.

        Raises:
            TerraformError: If any Terraform operation fails.
        """
        # Set up working directory
        self.reporter.start_step("Generating Terraform configuration")
        work_dir = self.setup_working_directory()
        self.reporter.success(f"Configuration written to {work_dir}")

        # Change to working directory
        original_dir = os.getcwd()
        os.chdir(work_dir)

        try:
            # Terraform init
            self.reporter.start_step("Initializing Terraform")
            self.reporter.info("Downloading providers (this may take a minute)...")
            self.init()
            self.reporter.success("Terraform initialized")

            # Terraform apply
            self.reporter.start_step("Deploying Agentless Scanner")
            self.reporter.info("Creating resources (this may take several minutes)...")
            self.apply()
            self.reporter.success("Resources created successfully")

        finally:
            os.chdir(original_dir)
