#!/bin/sh
export AIRFLOW__SCHEDULER__CATCHUP_BY_DEFAULT=True

export AIRFLOW__OPENLINEAGE__TRANSPORT='{"type": "http", "url": "https://startup-script-wins.invalid"}'
export AIRFLOW__OPENLINEAGE__NAMESPACE="startup-script-wins"

export AIRFLOW__OPENLINEAGE__CONFIG_PATH=""
export AIRFLOW__OPENLINEAGE__DISABLED_FOR_OPERATORS=""

export OPENLINEAGE_CLIENT_LOGGING=DEBUG
echo "AIRFLOW__OPENLINEAGE__TRANSPORT=${AIRFLOW__OPENLINEAGE__TRANSPORT}"
